import type { NextPage } from 'next'
import Head from 'next/head'

import Container from 'components/Container'
import Navbar from 'components/Navbar'

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar />
    <Container>
      <div>Teste</div>
    </Container>
  </div>
)

export default Home
