name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          yarn install
          yarn build
      - name: Deploy
        run: yarn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}
